generate:
    path: /generate
    controller: App\Controller\MainController::generate
    methods: ['POST']

history:
  path: /history
  controller: App\Controller\MainController::history
  methods: ['GET']
